In [2]:
!pip install numpy

  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)


In [7]:
import numpy as np

## Create array using numpy
## Create a 1D aray
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1.reshape(1,5)  ## 1 row 5 column

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)   # 2D array.
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array :", arr)
print("Shape:",arr.shape)
print("Number of dimenssion :", arr.ndim)
print("Size number of element:",arr.size)
print("Data type :", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array : [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimenssion : 2
Size number of element: 6
Data type : int64
Item size (in bytes): 8


In [20]:
## Numpy vetorized Operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:", arr1 + arr2)

## Element wise substration
print("Substraction :", arr1 - arr2)

# Elements wise multiplication
print("Substraction :", arr1 * arr2)

# Element wise divison
print("Substraction :", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction : [ -9 -18 -27 -36 -45]
Substraction : [ 10  40  90 160 250]
Substraction : [0.1 0.1 0.1 0.1 0.1]


In [25]:
# Universal Function

arr = np.array([1,2,3,4,5])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## sin
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [27]:
## Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)




Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
## indexing

arr[0][0]

np.int64(1)

In [29]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [30]:
## Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:] = 50
print(arr)

[[100   2   3   4]
 [ 50  50  50  50]
 [ 50  50  50  50]]


In [32]:
## Statistical concepts - Normalization
## to have mean of 0 and stadard deviation of 1

data = np.array([1,2,3,4,5])
## Calculate the mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean)/std_dev
print("Normalized data :", normalized_data)

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print("Mean :", mean)

median = np.median(data)
print("Median : ", median)

std_dev = np.std(data)
print("Standard deviation:",std_dev)

variance = np.var(data)
print("Variance :",variance)

Mean : 5.5
Median :  5.5
Standard deviation: 2.8722813232690143
Variance : 8.25


In [37]:
## Logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data > 5]

array([ 6,  7,  8,  9, 10])

In [38]:

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data <=8)]

array([6, 7, 8])