In [4]:
import numpy as np
import pandas as pd

df =pd.read_csv('student_scores.csv')
df


Subject_1  Subject_2  Subject_3  Subject_4  Subject_5
0      58.76      72.56      48.30      81.17      61.03
1      77.95      40.38      62.49      93.76      84.19
2      65.07      42.89      64.12      91.05      44.74
3      79.26      85.54      85.68      77.20      95.60
4      53.39      58.72      95.67      50.71      81.21
5      55.92      91.67      67.73      80.45      50.41
6      68.47      67.26      73.76      92.02      51.82
7      51.90      91.53      91.53      57.77      91.15
8      43.23      99.61      48.09      67.32      89.14
9      98.53      70.11      77.38      93.85      42.44

In [9]:
data_array = np.genfromtxt('student_scores.csv',delimiter=',',filling_values=0)
print(data_array)

[[ 0.    0.    0.    0.    0.  ]
 [58.76 72.56 48.3  81.17 61.03]
 [77.95 40.38 62.49 93.76 84.19]
 [65.07 42.89 64.12 91.05 44.74]
 [79.26 85.54 85.68 77.2  95.6 ]
 [53.39 58.72 95.67 50.71 81.21]
 [55.92 91.67 67.73 80.45 50.41]
 [68.47 67.26 73.76 92.02 51.82]
 [51.9  91.53 91.53 57.77 91.15]
 [43.23 99.61 48.09 67.32 89.14]
 [98.53 70.11 77.38 93.85 42.44]]


In [15]:
df = pd.read_csv('student_scores.csv', delimiter=',', skiprows=1)
# print(df)
data = df.values
print(data)

[[77.95 40.38 62.49 93.76 84.19]
 [65.07 42.89 64.12 91.05 44.74]
 [79.26 85.54 85.68 77.2  95.6 ]
 [53.39 58.72 95.67 50.71 81.21]
 [55.92 91.67 67.73 80.45 50.41]
 [68.47 67.26 73.76 92.02 51.82]
 [51.9  91.53 91.53 57.77 91.15]
 [43.23 99.61 48.09 67.32 89.14]
 [98.53 70.11 77.38 93.85 42.44]]


In [16]:
# sum along axis=1 to get row wise totla

total_marks = np.sum(data, axis=1)

print("Totla marks for each student")
print(total_marks)

Totla marks for each student
[358.77 307.87 423.28 339.7  346.18 353.33 383.88 347.39 382.31]


In [17]:
avg_marks = np.average(data, axis=1)
print(avg_marks)

[71.754 61.574 84.656 67.94  69.236 70.666 76.776 69.478 76.462]


In [20]:
data = df.values

total_marks = np.sum(data, axis=1)

top_index = np.argmax(total_marks)

# get top student detailes
top_student = df.iloc[top_index]
print(top_student)

58.76    79.26
72.56    85.54
48.3     85.68
81.17    77.20
61.03    95.60
Name: 2, dtype: float64


In [22]:
data = df.values

condition = np.any(data > 90, axis=1)

count = np.sum(condition)
print(f"Number of student who scored 90 in any subject : {count}")

Number of student who scored 90 in any subject : 9


In [24]:
data = df.values

# compute mean std dev per subject
means = np.mean(data, axis = 0)
stds = np.std(data, axis=0)

z_scores = (data - means)/stds

z_df = pd.DataFrame(z_scores, columns=df.columns)

print(z_df.head(5))

      58.76     72.56      48.3     81.17     61.03
0  0.739617 -1.544685 -0.802935  1.006543  0.677245
1 -0.055490 -1.421942 -0.689719  0.830825 -1.215958
2  0.820486  0.663700  0.807797 -0.067218  1.224810
3 -0.776519 -0.647834  1.501684 -1.784847  0.534235
4 -0.620337  0.963465 -0.438975  0.143514 -0.943855


In [25]:
z_df.describe()

58.76         72.56          48.3         81.17         61.03
count  9.000000e+00  9.000000e+00  9.000000e+00  9.000000e+00  9.000000e+00
mean   3.454027e-16 -1.495717e-16 -5.982869e-16  1.233581e-16 -2.713879e-16
std    1.060660e+00  1.060660e+00  1.060660e+00  1.060660e+00  1.060660e+00
min   -1.403716e+00 -1.544685e+00 -1.803132e+00 -1.784847e+00 -1.326335e+00
25%   -7.765191e-01 -6.478341e-01 -6.897188e-01 -7.078437e-01 -9.438553e-01
50%   -5.549015e-02 -9.084782e-02 -2.014284e-02  1.435140e-01  5.342346e-01
75%    7.396171e-01  9.566189e-01  8.077975e-01  8.937202e-01  9.147947e-01
max    2.010060e+00  1.351742e+00  1.501684e+00  1.012379e+00  1.224810e+00

In [27]:
data = df.values

total_scores = np.sum(data, axis=1)

# get sorting index descending
sorted_indices = np.argsort(-total_scores)
print(sorted_indices)

[2 6 8 0 5 7 4 3 1]


In [29]:
df_sorted = df.iloc[sorted_indices].copy()
print(df_sorted)

   58.76  72.56   48.3  81.17  61.03
2  79.26  85.54  85.68  77.20  95.60
6  51.90  91.53  91.53  57.77  91.15
8  98.53  70.11  77.38  93.85  42.44
0  77.95  40.38  62.49  93.76  84.19
5  68.47  67.26  73.76  92.02  51.82
7  43.23  99.61  48.09  67.32  89.14
4  55.92  91.67  67.73  80.45  50.41
3  53.39  58.72  95.67  50.71  81.21
1  65.07  42.89  64.12  91.05  44.74


In [30]:
df_sorted["Total"] = total_scores[sorted_indices]
df["Rank"] = range(1, len(df_sorted) + 1)

print(df_sorted.head)

<bound method NDFrame.head of    58.76  72.56   48.3  81.17  61.03   Total
2  79.26  85.54  85.68  77.20  95.60  423.28
6  51.90  91.53  91.53  57.77  91.15  383.88
8  98.53  70.11  77.38  93.85  42.44  382.31
0  77.95  40.38  62.49  93.76  84.19  358.77
5  68.47  67.26  73.76  92.02  51.82  353.33
7  43.23  99.61  48.09  67.32  89.14  347.39
4  55.92  91.67  67.73  80.45  50.41  346.18
3  53.39  58.72  95.67  50.71  81.21  339.70
1  65.07  42.89  64.12  91.05  44.74  307.87>


In [31]:
data = df.values
print(data)

[[77.95 40.38 62.49 93.76 84.19  1.  ]
 [65.07 42.89 64.12 91.05 44.74  2.  ]
 [79.26 85.54 85.68 77.2  95.6   3.  ]
 [53.39 58.72 95.67 50.71 81.21  4.  ]
 [55.92 91.67 67.73 80.45 50.41  5.  ]
 [68.47 67.26 73.76 92.02 51.82  6.  ]
 [51.9  91.53 91.53 57.77 91.15  7.  ]
 [43.23 99.61 48.09 67.32 89.14  8.  ]
 [98.53 70.11 77.38 93.85 42.44  9.  ]]


In [32]:
df

58.76  72.56   48.3  81.17  61.03  Rank
0  77.95  40.38  62.49  93.76  84.19     1
1  65.07  42.89  64.12  91.05  44.74     2
2  79.26  85.54  85.68  77.20  95.60     3
3  53.39  58.72  95.67  50.71  81.21     4
4  55.92  91.67  67.73  80.45  50.41     5
5  68.47  67.26  73.76  92.02  51.82     6
6  51.90  91.53  91.53  57.77  91.15     7
7  43.23  99.61  48.09  67.32  89.14     8
8  98.53  70.11  77.38  93.85  42.44     9

In [33]:
# calculate column-wise variance and standard deviation
variances = np.var(data, axis = 0)
std_devs = np.std(data, axis =0)

# Display with subjectt names
for i, column in enumerate(df.columns):
    print(f"{column}: Variance = {variances[i]:.2f}, Standard Deviation = {std_devs[i]:.2f}")

58.76: Variance = 262.41, Standard Deviation = 16.20
72.56: Variance = 418.18, Standard Deviation = 20.45
48.3: Variance = 207.28, Standard Deviation = 14.40
81.17: Variance = 237.85, Standard Deviation = 15.42
61.03: Variance = 434.21, Standard Deviation = 20.84
Rank: Variance = 6.67, Standard Deviation = 2.58


In [35]:
## Practice on city_temperatures.csv files
data_array = pd.read_csv('city_temperatures.csv', delimiter=',')
print(data_array)

   City_A  City_B  City_C  City_D
0    33.4    26.2    30.3    40.7
1    35.4    32.7    39.9    29.3
2    30.2    38.7    28.4    33.5
3    25.1    41.8    30.7    38.1
4    38.6    40.9    30.3    34.6
5    38.0    32.6    37.2    36.2
6    35.7    36.7    40.1    37.7


In [36]:
data = df.values
print(data)

[[77.95 40.38 62.49 93.76 84.19  1.  ]
 [65.07 42.89 64.12 91.05 44.74  2.  ]
 [79.26 85.54 85.68 77.2  95.6   3.  ]
 [53.39 58.72 95.67 50.71 81.21  4.  ]
 [55.92 91.67 67.73 80.45 50.41  5.  ]
 [68.47 67.26 73.76 92.02 51.82  6.  ]
 [51.9  91.53 91.53 57.77 91.15  7.  ]
 [43.23 99.61 48.09 67.32 89.14  8.  ]
 [98.53 70.11 77.38 93.85 42.44  9.  ]]


In [39]:
fahrenheit = (data * 9/5) + 32

df_fahrenheit = pd.DataFrame(fahrenheit, columns=df.columns)

print("Temperatures in fehrenheit")
print(f"{df_fahrenheit}:.2f")

Temperatures in fehrenheit
     58.76    72.56     48.3    81.17    61.03  Rank
0  172.310  104.684  144.482  200.768  183.542  33.8
1  149.126  109.202  147.416  195.890  112.532  35.6
2  174.668  185.972  186.224  170.960  204.080  37.4
3  128.102  137.696  204.206  123.278  178.178  39.2
4  132.656  197.006  153.914  176.810  122.738  41.0
5  155.246  153.068  164.768  197.636  125.276  42.8
6  125.420  196.754  196.754  135.986  196.070  44.6
7  109.814  211.298  118.562  153.176  192.452  46.4
8  209.354  158.198  171.284  200.930  108.392  48.2:.2f


In [40]:
data = df.values

daily_avg = np.mean(data, axis=1)

df["Daily_Avg_Temp"] = np.round(daily_avg,2)

print(df["Daily_Avg_Temp"])

0    59.96
1    51.64
2    71.05
3    57.28
4    58.53
5    59.89
6    65.15
7    59.23
8    65.22
Name: Daily_Avg_Temp, dtype: float64


In [42]:
data = df.values
cities = df.columns

max_temp = np.max(data)
day_idx, city_idx = np.unravel_index(np.argmax(data), data.shape)

city_with_max_temp = cities[city_idx]
day_number =  day_idx + 1

print(f"🔥 Highest temperature was {max_temp}°C on Day {day_number} in {city_with_max_temp}.")

🔥 Highest temperature was 99.61°C on Day 8 in 72.56.


In [44]:
data = df.values

days_all_above_35 = np.all(data > 35, axis =1)

days = np.where(days_all_above_35)[0] + 1

if len(days) ==0:
    print("No days found where all cities had temperature above 35")
else:
    print(f"Days when all cities were above 35C :{days}")

No days found where all cities had temperature above 35


In [45]:
days_all_above_35

array([False, False, False, False, False, False, False, False, False])

In [46]:
df_cleaned = df.mask(df > 40)

print(df_cleaned)

   58.76  72.56  48.3  81.17  61.03  Rank  Daily_Avg_Temp
0    NaN    NaN   NaN    NaN    NaN     1             NaN
1    NaN    NaN   NaN    NaN    NaN     2             NaN
2    NaN    NaN   NaN    NaN    NaN     3             NaN
3    NaN    NaN   NaN    NaN    NaN     4             NaN
4    NaN    NaN   NaN    NaN    NaN     5             NaN
5    NaN    NaN   NaN    NaN    NaN     6             NaN
6    NaN    NaN   NaN    NaN    NaN     7             NaN
7    NaN    NaN   NaN    NaN    NaN     8             NaN
8    NaN    NaN   NaN    NaN    NaN     9             NaN


In [47]:
## Practice on patient_vitals.csv

import pandas as pd
import numpy as np

df = pd.read_csv('patient_vitals.csv')
vitals_array = df.values
print(vitals_array)

[[ 79.  105.9  98.3]
 [ 74.  110.1  99.3]
 [ 71.8 105.1  98.9]
 [ 64.4 135.3  99.2]
 [ 75.8 129.4  97.9]
 [ 77.7 126.6  99.6]
 [ 67.9 121.3  98.2]
 [ 81.4 116.3  98.4]
 [ 77.4 135.4  98.4]
 [ 84.1 129.9  98.9]
 [ 72.1 116.4  98.8]
 [ 71.7 116.8  99.1]
 [ 71.3 121.1  98. ]
 [ 77.5 143.5  97.6]
 [ 77.3 138.2  99.1]]


In [48]:
vitals = df.values

avg_vitals = np.mean(vitals, axis=0)

for col, avg in zip(df.columns, avg_vitals):
    print(f"Average {col} : {avg:.2f}")

Average HeartRate : 74.89
Average BloodPressure : 123.42
Average Temperature : 98.65


In [ ]:
df = pd.read_csv('patient_vitals.csv')

bp = df["BloodPressure"].values

Q1 = np.percentile(bp, 25)
Q3 = np.percentile(bp, 75)
IQR = Q3 - Q1


lower_bond = Q1 - 1.5 *IQR
upper_bond = Q3 + 1.5 * IQR
